server:
  port: 60001
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    # 最大吞吐量不限制
    max-swallow-size: -1
  # 优雅停机 关闭容器后默认等待30秒继续执行没处理完的任务 避免数据不一致
  shutdown: graceful
spring:
  lifecycle:
    # 配置优雅停机后的缓冲器 最大等待时间
    timeout-per-shutdown-phase: 10S
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/medicine?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 1000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # Redis
  redis:
    host: 127.0.0.1
    # password:
    # 数据库索引 默认0
    database: 1
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
xboot:
  # 全局限流
  ratelimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制200个请求
    limit: 200
  # IP限流
  iplimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 每个ip限制30个请求
    limit: 30
  # 后台token交互方式
  token:
    # 默认为true，token将存入redis，并具有单点登录功能 设为false使用JWT交互
    redis: true
    # 是否开启单设备登陆 仅当token交互方式为redis时生效
    sdl: true
    # token中存储用户权限数据 开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间 redis模式有请求自动刷新（分钟）
    tokenExpireTime: 60
    # 用户选择 保存登录状态/记住我 对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  # 使用Spring @Cacheable注解失效时间
  cache:
    # 过期时间单位 支持day、hour、minute对应天、小时、分钟
    unit: day
    # 过期时间 永久不过期设为-1
    time: 15
  # 腾讯位置服务key配置 腾讯位置服务官网注册添加key
  qqlbs:
    key: MKDBZ-G2ERX-TMT4G-TDIUX-KGWSS-5AFOP

# 需要验证码校验的接口路径 支持通配符 自动过滤拦截校验 无需开发人员再次校验
captcha:
  # 图片验证码验证
  image:
    - /zwz/login # 登录接口
    - /zwz/oauth2/authorize # 认证接口
  # 短信验证码验证
  sms:
    - /zwz/user/regist # 注册接口
    - /zwz/user/smsLogin # 短信登录接口
    - /zwz/user/resetByMobile # 手机重置密码
    - /zwz/user/changeMobile # 更换绑定手机
    - /zwz/app/v1/member/quickLogin # 会员快捷登录注册接口
  # Vaptcha验证码验证
  vaptcha:
    - /zwz/common/captcha/sendRegistSms/** # 发送注册短信
    - /zwz/common/captcha/sendResetSms/** # 发送重置密码短信
    - /zwz/email/sendResetCode/** # 发送重置密码邮件
    - /zwz/social/relate # 绑定第三方账号
  # Email验证码验证
  email:
    - /zwz/email/resetByEmail # 邮件重置密码
    - /zwz/email/editEmail # 修改绑定邮箱

# 忽略url
ignored:
  urls:
    - /zwz/**/**
    - /zwz/app/v1/**
    - /zwz/oauth2/**
    - /zwz/actuator/**
    - /zwz/admin/**
    - /editor-app/**
    - /zwz/act/**
    - /zwz/dictData/getByType/**
    - /zwz/email/sendResetCode/**
    - /zwz/email/resetByEmail
    - /zwz/file/view/**
    - /zwz/social/**
    - /zwz/ws/**
    - /zwz/setting/notice
    - /zwz/user/regist
    - /zwz/user/smsLogin
    - /zwz/user/resetByMobile
    - /zwz/common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /zwz/test/**
  # 限流及黑名单不拦截的路径
  limitUrls:
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico

# Actuator
management:
  health:
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          DOWN: 200
          OUT_OF_SERVICE: 200
          FATAL: 200
          UNKNOWN: 200
  endpoints:
    web:
      base-path: /zwz/actuator/
      exposure:
        include: '*'

# Swagger界面内容配置
swagger:
  title: 城乡大病保险管理系统
  description: 城乡大病保险管理系统接口文档
  version: 1.0.0
  termsOfServiceUrl: http://zwz.cn
  contact:
    name: 郑为中
    url: http://zwz.cn
    email: 916077357@qq.com

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

# 日志
logging:
  # 输出级别
  level:
    root: info
  file:
    # 指定路径
    path: logs
    # 最大保存天数
    max-history: 7
    # 每个文件最大大小
    max-size: 5MB